import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home({title}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
            <nav>
                <div className="header-logo-container">
                    <Image
                      src='../public/'
                      alt='profile picture' 
                      className='header-pp-img'/>
                    <span className="header-logo-title">Museum Calendar</span>
                </div>

                <div className='nav-list'>
                    <a className='nav-item' href='/'>Accueil</a>
                    <a className='nav-item' href='/events'>Expositions</a>
                    <a className='nav-item' href='/about-us'>Musées</a>
                </div>
            </nav>
        </header>

      <main className={styles.main}>
        <a href='/events/london'>
          <img />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>
        </a>

        <a href='/events/sanfrancisco'>
          <img />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>
        </a>

        <a href='/events/barcelona'>
          <img />
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          </p>
        </a>
      </main>

      <footer className={styles.footer}>
        <p>
          2023 Time to code - NextJS Project
        </p>
      </footer>
    </div>
  )
}

export function getServerSideProps() {
  return {
      props:{
          title: 'Hello everyone'
      }
  }
}