import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { HomePage } from '../src/components/home/home-page'
import { Header } from '../src/components/header/header'
import { Footer } from '../src/components/footer/footer'


export default function Home({title}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <HomePage />

      <Footer />
    </div> 
  )
}

export function getServerSideProps() {
  return {
      props:{
          title: 'Hello everyone'
      }
  }
}